# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст відповіді')),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='images/answer', verbose_name='Зображення')),
                ('answer_correct', models.BooleanField(default=False, verbose_name='Правильна/неправильна')),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст питання')),
                ('question_alias', models.SlugField(verbose_name='Alias питання')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='images/question', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200, verbose_name='Назва розділу')),
                ('section_alias', models.SlugField(verbose_name='Alias розділу')),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='images/section', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Розділ',
                'verbose_name_plural': 'Розділи',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200, verbose_name='Назва тесту')),
                ('test_alias', models.SlugField(verbose_name='Alias тесту')),
                ('test_image', models.ImageField(blank=True, null=True, upload_to='images/test', verbose_name='Зображення')),
                ('test_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Section', verbose_name='Розділ')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_parretn_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Test', verbose_name='Тест(батьківський)'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_parretn_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Question', verbose_name='Питання(батьківське)'),
        ),
    ]
